name: avionix_airflow
dependencies:
  - pip

  # Test requirements
  - black
  - flake8
  - mypy
  - isort
  - pytest
  - pandas
  - requests
  - pytest
  - pytest-rerunfailures
  - pip:
    # Main requirements
    - avionix==0.4.4
    - python-hosts==1.0.0
    - cryptography==3.2
    # Only available on pip
    - pytest-cases==2.3.0

