apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: airflow
  name: dag-sync-job
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::490886070143:role/HmiOpsDagSyncRoleStagingEc2
          labels:
            app: airflow
          name: sync-dags-pod
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - aws s3 sync s3://hmi-spire-airflow-staging-us-east-1/dags /usr/local/airflow/dags
              --delete --exact-timestamps; find /usr/local/airflow/dags/* -empty -type
              d -delete;
            image: amazon/aws-cli
            imagePullPolicy: IfNotPresent
            name: sync-dag-container
            volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: dags
          restartPolicy: OnFailure
          volumes:
          - name: dags
            persistentVolumeClaim:
              claimName: dags
              readOnly: false
  schedule: '* * * * *'
