{
 "title": "Airflow Monitoring",
 "description": "Useful for monitoring an airflow kubernetes cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dag_id", "query": "SELECT\n\ndag_id\nFROM dag\n" }
  ]
 },
 "panels": [
  { "title": "Dag Specific Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DAG Schedule Delay",
   "type": "stat",
   "description": "Milliseconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_dag_processing_last_run_seconds_ago_${dag_id}_dag.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dag Logs",
   "type": "logs",
   "description": "Logs specific to the selected dag",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.labels.dag_id:$dag_id",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Scheduler Heart Beats",
   "type": "gauge",
   "description": "This determines the responsiveness of the scheduler, should not drop below 1",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_scheduler_heartbeat.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tasks - Running",
   "type": "stat",
   "description": "The number of airflow tasks running",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_executor_running_tasks.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tasks - Queued",
   "type": "stat",
   "description": "The number of airflow tasks queued to run",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_executor_queued_tasks.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Open Executor Slots",
   "type": "stat",
   "description": "The number of slots available for task to be run",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_executor_open_slots.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Scheduler Logs",
   "type": "logs",
   "description": "Logs from the airflow scheduler",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.container.name:scheduler",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Overall Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "DAG bag size",
   "type": "stat",
   "description": "DAG bag size",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_dagbag_size.value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average DAG parse time (seconds)",
   "type": "stat",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_dag_processing_total_parse_time.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Sync Time",
   "type": "stat",
   "description": "How long ago the DAGs were synced",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_dag_processing_last_run_seconds_ago*",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "@timestamp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Task - Successes",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_ti_successes.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Task - Failures",
   "type": "stat",
   "description": "Overall task instances failures",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "airflow_ti_failures.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}